apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: youtube
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      upstream frontend {
        server youtube.youtube.svc.cluster.local:80;  
      }

      upstream backend {
        server youtube-backend.youtube.svc.cluster.local:5000;  
      }

      server {
        listen 80;

        # Proxy for the frontend
        location / {
          proxy_pass http://frontend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Proxy for the backend (example: /api could be the path for backend)
        location /api {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
