---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
  namespace: youtube
  labels:
    app: youtube-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-frontend
  template:
    metadata:
      labels:
        app: youtube-frontend
    spec:
      containers:
      - name: youtube-frontend
        image: janisadhi/frontend-youtube:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet: 
            port: 80
            path: /
          initialDelaySeconds: 10  
          periodSeconds: 5  
          failureThreshold: 3  
          timeoutSeconds: 2 